# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 00:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('language', models.CharField(blank=True, max_length=20)),
                ('currency', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceprovidors.Provider')),
            ],
        ),
    ]
